# This file was generated by update.sh

{
  "kicad" = {
    kicadVersion = {
      version =			"5.1.9";
      src = {
        rev =			"73d0e3b20dec05c4350efa5b69916eb29a7bfcb5";
        sha256 =		"1cqh3bc9y140hbryfk9qavs2y3lj5sm9q0qjxcf4mm472afzckky";
      };
    };
    libVersion = {
      version =			"5.1.9";
      libSources = {
        i18n.rev =		"04f3231f60d55400cb81564b2cd465a57d5192d5";
        i18n.sha256 =		"04jq1dcag6i2ljjfqrib65mn4wg4c4nmi7i946l3bywc0rkqsx1f";
        symbols.rev =		"6dec5004b6a2679c19d4857bda2f90c5ab3a5726";
        symbols.sha256 =	"0n25rq32jwyigfw26faqraillwv6zbi2ywy26dkz5zqlf5xp56ad";
        templates.rev =		"1ccbaf3704e8ff4030d0915f71e051af621ef7d7";
        templates.sha256 =	"1a8xfcbdbb4ylrb5m7n2jjk9kwvgmlx1pmnn2cwj327a2b3m4jjs";
        footprints.rev =	"302ac78bac21825532f970fb92714fa5973ad79b";
        footprints.sha256 =	"0gyqxryda273hjn2rv8dha461j9bjh054y5dlpiw1wiha65lrf9i";
        packages3d.rev =	"7abe02f30fd79b8f4f66c01589861df7f8f72f04";
        packages3d.sha256 =	"1szcin52fcsyb55bj7xq7lz6ig187dpz3lk7blwab7b9c4dn3c3y";
      };
    };
  };
  "kicad-unstable" = {
    kicadVersion = {
      version =			"2021-01-18";
      src = {
        rev =			"50e22de3ba3ab3008bbee8d8a5773716e114e3ad";
        sha256 =		"1kprajbvqvx3x9hy0673nyw03sq4wx0crzjg1cgg9gsjzrkx9vl2";
      };
    };
    libVersion = {
      version =			"2021-01-18";
      libSources = {
        i18n.rev =		"e89d9a89bec59199c1ade56ee2556591412ab7b0";
        i18n.sha256 =		"04zaqyhj3qr4ymyd3k5vjpcna64j8klpsygcgjcv29s3rdi8glfl";
        symbols.rev =		"e012b90c1669210ff153288a45d1003b6afde677";
        symbols.sha256 =	"1wjv6h5rrnh582vzfbh8bh5xwcz1d61vkz73049b8f66qjz2c1ym";
        templates.rev =		"f99cc6dc52b524977d946438d0c27de122dc8766";
        templates.sha256 =	"00ninfpmia96yzy54lf7866d5j83bg70wf025rmyjcm6g850j8s4";
        footprints.rev =	"2ba0d5cb6a5649de2e9d64c8f952b4c0984c7b6d";
        footprints.sha256 =	"0np9qckccq3bh8mz94zr1fv5k436v02p8sfx4r1b26fnmbylr41w";
        packages3d.rev =	"d8b7e8c56d535f4d7e46373bf24c754a8403da1f";
        packages3d.sha256 =	"0dh8ixg0w43wzj5h3164dz6l1vl4llwxhi3qcdgj1lgvrs28aywd";
      };
    };
  };
}
